version: "3.9"

services:

  webhook:
    build: ./webhook
    container_name: webhook-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_URL=http://processor:9001/process
    ports:
      - "9000:9000"
#    depends_on:
#      - redis

#processor:
#  build: ./processor
#  container_name: processor-service
#  restart: unless-stopped
#  environment:
#    - SPRING_PROFILES_ACTIVE=dev
#    - REDIS_HOST=redis
#    - REDIS_PORT=6379
#  ports:
#    - "9000:9000"
#  depends_on:
#    - redis
#
#  redis:
#    image: redis:7-alpine
#    container_name: redis-db
#    restart: unless-stopped
#    command: ["redis-server", "--appendonly", "yes"]
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#
#  ngrok:
#    image: ngrok/ngrok:latest
#    container_name: ngrok-tunnel
#    environment:
#      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
#    command:
#      - "http"
#      - "webhook:8080"
#    ports:
#      - "4040:4040"
#    depends_on:
#      - webhook

#volumes:
#  redis-data: